/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jStatementOfAccount;

/**
 *
 * @author jabi
 */
public class JavaStatementOfAccountSlip extends javax.swing.JFrame {
    
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JavaStatementOfAccountSlip.class.getName());
            public JavaStatementOfAccountSlip(String id, String name, String course,
                         double tuitionFee, String scholarship,
                         double misc, double balance) {
    /**
     * Creates new form JavaStatementOfAccountSlip
     */
    
        initComponents();
        
        lblID.setText(id);
        lblName.setText(name);
        lblCourse.setText(course);
        lblTuition.setText(String.format("₱ %.2f", tuitionFee));
        lblScholarship.setText(scholarship);
        lblMisc.setText(String.format("₱ %.2f", misc));
        lblBalance.setText(String.format("₱ %.2f", balance));
    }

    private JavaStatementOfAccountSlip() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblTuition = new javax.swing.JLabel();
        lblScholarship = new javax.swing.JLabel();
        lblMisc = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATEMENT OF ACCOUNT SLIP");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 290, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID NUMBER :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 100, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 70, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COURSE :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 90, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TUITION FEE : ");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 100, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SCHOLARSHIP :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 260, 120, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MISCELLANEOUS : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 300, 140, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OUTSTANDING BALANCE : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 340, 190, 17);

        lblID.setBackground(new java.awt.Color(255, 255, 255));
        lblID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblID);
        lblID.setBounds(250, 90, 160, 30);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblName);
        lblName.setBounds(250, 130, 160, 30);

        lblCourse.setBackground(new java.awt.Color(255, 255, 255));
        lblCourse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblCourse);
        lblCourse.setBounds(250, 170, 160, 30);

        lblTuition.setBackground(new java.awt.Color(255, 255, 255));
        lblTuition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTuition.setForeground(new java.awt.Color(255, 255, 255));
        lblTuition.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblTuition);
        lblTuition.setBounds(250, 210, 160, 30);

        lblScholarship.setBackground(new java.awt.Color(255, 255, 255));
        lblScholarship.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblScholarship.setForeground(new java.awt.Color(255, 255, 255));
        lblScholarship.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblScholarship);
        lblScholarship.setBounds(250, 250, 160, 30);

        lblMisc.setBackground(new java.awt.Color(255, 255, 255));
        lblMisc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMisc.setForeground(new java.awt.Color(255, 255, 255));
        lblMisc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblMisc);
        lblMisc.setBounds(250, 290, 160, 30);

        lblBalance.setBackground(new java.awt.Color(255, 255, 255));
        lblBalance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblBalance);
        lblBalance.setBounds(250, 330, 160, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jStatementOfAccount/images/12 (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 440, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JavaStatementOfAccountSlip().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMisc;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblScholarship;
    private javax.swing.JLabel lblTuition;
    // End of variables declaration//GEN-END:variables
}
