/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jStatementOfAccount;

/**
 *
 * @author jabi
 */
public class JavaStatementOfAccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JavaStatementOfAccount.class.getName());

    /**
     * Creates new form JavaStatementOfAccount
     */
    public JavaStatementOfAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtUnitsEnrolled = new javax.swing.JTextField();
        cmbScholarships = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chkLibrary = new javax.swing.JRadioButton();
        chkLaboratory = new javax.swing.JRadioButton();
        chkClinic = new javax.swing.JRadioButton();
        chkLMS = new javax.swing.JRadioButton();
        btnConfirm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StatementOfAccount");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATEMENT OF ACCOUNT");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 290, 32);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 63, 14);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 33, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COURSE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 48, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UNITS ENROLLED");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 190, 98, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SCHOLARSHIPS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 230, 108, 17);

        txtIdNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        getContentPane().add(txtIdNumber);
        txtIdNumber.setBounds(150, 80, 150, 22);

        txtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        getContentPane().add(txtName);
        txtName.setBounds(150, 110, 150, 22);

        txtCourse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        getContentPane().add(txtCourse);
        txtCourse.setBounds(150, 140, 150, 22);

        txtUnitsEnrolled.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        txtUnitsEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitsEnrolledActionPerformed(evt);
            }
        });
        getContentPane().add(txtUnitsEnrolled);
        txtUnitsEnrolled.setBounds(150, 180, 149, 22);

        cmbScholarships.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbScholarships.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRESIDENTIAL", "ACADEMIC", "WORKING", "ATHELETIC", "SUGBO" }));
        cmbScholarships.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        cmbScholarships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbScholarshipsActionPerformed(evt);
            }
        });
        getContentPane().add(cmbScholarships);
        cmbScholarships.setBounds(150, 220, 150, 27);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MISCELLANOUS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 110, 17);

        chkLibrary.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkLibrary.setForeground(new java.awt.Color(255, 255, 255));
        chkLibrary.setText("LIBRARY");
        chkLibrary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 255, 0), new java.awt.Color(0, 255, 255)));
        chkLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLibraryActionPerformed(evt);
            }
        });
        getContentPane().add(chkLibrary);
        chkLibrary.setBounds(30, 300, 100, 21);

        chkLaboratory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkLaboratory.setForeground(new java.awt.Color(255, 255, 255));
        chkLaboratory.setText("LABORATORY");
        chkLaboratory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkLaboratory);
        chkLaboratory.setBounds(30, 320, 120, 21);

        chkClinic.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkClinic.setForeground(new java.awt.Color(255, 255, 255));
        chkClinic.setText("CLINIC");
        chkClinic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkClinic);
        chkClinic.setBounds(30, 340, 90, 21);

        chkLMS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkLMS.setForeground(new java.awt.Color(255, 255, 255));
        chkLMS.setText("LMS");
        chkLMS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkLMS);
        chkLMS.setBounds(30, 360, 70, 21);

        btnConfirm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConfirm.setText("CONFIRM");
        btnConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(290, 390, 100, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jStatementOfAccount/images/12 (1).jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 440, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
                                                                                       
        String id = txtIdNumber.getText();
        String name = txtName.getText();
        String course = txtCourse.getText();

        int units = Integer.parseInt(txtUnitsEnrolled.getText());
        double tfPerUnit = 981.5;
        double tuitionFee = units * tfPerUnit;

        
        String scholarship = cmbScholarships.getSelectedItem().toString();
        double discountRate = 0;

        switch (scholarship.toLowerCase()) {
            case "presidential": discountRate = 0.90; break;
            case "academic": discountRate = 0.80; break;
            case "working": discountRate = 0.90; break;
            case "atheletic": discountRate = 0.70; break;
            case "sugbo": discountRate = 0.20; break;
        }

        double discountAmount = tuitionFee * discountRate;
        double discountedTuition = tuitionFee - discountAmount;

        
        double miscFee = 0;

        if (chkLibrary.isSelected()) miscFee += 1500;
        if (chkLaboratory.isSelected()) miscFee += 1000;
        if (chkClinic.isSelected()) miscFee += 1000;
        if (chkLMS.isSelected()) miscFee += 1000;

        double outstandingBalance = discountedTuition + miscFee;

        
        JavaStatementOfAccountSlip slip = new JavaStatementOfAccountSlip(id, name, course, tuitionFee,
                scholarship, miscFee, outstandingBalance);

        slip.setVisible(true);
        this.dispose(); 


       
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cmbScholarshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbScholarshipsActionPerformed
        
    }//GEN-LAST:event_cmbScholarshipsActionPerformed

    private void txtUnitsEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitsEnrolledActionPerformed
        
    }//GEN-LAST:event_txtUnitsEnrolledActionPerformed

    private void chkLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLibraryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JavaStatementOfAccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JRadioButton chkClinic;
    private javax.swing.JRadioButton chkLMS;
    private javax.swing.JRadioButton chkLaboratory;
    private javax.swing.JRadioButton chkLibrary;
    private javax.swing.JComboBox<String> cmbScholarships;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtIdNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUnitsEnrolled;
    // End of variables declaration//GEN-END:variables
}
