/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jSOA;

/**
 *
 * @author jabi
 */
public class JavaSOA extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JavaSOA.class.getName());

    /**
     * Creates new form JavaSOA
     */
    public JavaSOA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUnits = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbYear = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbScholarship = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chkLibrary = new javax.swing.JCheckBox();
        chkLaboratory = new javax.swing.JCheckBox();
        chkClinic = new javax.swing.JCheckBox();
        chkLms = new javax.swing.JCheckBox();
        btnProceed = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 109, 49, 17);

        txtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(60, 132, 292, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID NUMBER :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 166, 88, 17);

        txtID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtID);
        txtID.setBounds(60, 189, 292, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("COURSE :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 223, 67, 17);

        txtCourse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCourse);
        txtCourse.setBounds(60, 246, 292, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UNITS ENROLLED :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 280, 128, 17);

        txtUnits.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtUnits);
        txtUnits.setBounds(60, 303, 292, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("YEAR LEVEL :");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 337, 93, 17);

        cmbYear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st YEAR", "2nd YEAR", "3rd YEAR", "4th YEAR" }));
        cmbYear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbYear);
        cmbYear.setBounds(60, 360, 292, 24);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SCHOLARSHIP :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 443, 107, 17);

        cmbScholarship.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbScholarship.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "PRESIDENTIAL", "ACADEMIC", "WORKING", "ATHLETIC", "SUGBO" }));
        cmbScholarship.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbScholarship);
        cmbScholarship.setBounds(60, 466, 292, 24);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MISCELLANEOUS : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 496, 131, 17);

        chkLibrary.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkLibrary.setForeground(new java.awt.Color(255, 255, 255));
        chkLibrary.setText("LIBRARY");
        chkLibrary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkLibrary);
        chkLibrary.setBounds(60, 519, 120, 21);

        chkLaboratory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkLaboratory.setForeground(new java.awt.Color(255, 255, 255));
        chkLaboratory.setText("LABORATORY");
        chkLaboratory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkLaboratory);
        chkLaboratory.setBounds(60, 546, 140, 21);

        chkClinic.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkClinic.setForeground(new java.awt.Color(255, 255, 255));
        chkClinic.setText("CLINIC");
        chkClinic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkClinic);
        chkClinic.setBounds(60, 573, 110, 21);

        chkLms.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkLms.setForeground(new java.awt.Color(255, 255, 255));
        chkLms.setText("LMS");
        chkLms.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(chkLms);
        chkLms.setBounds(60, 600, 120, 21);

        btnProceed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnProceed.setText("PROCEED");
        btnProceed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });
        getContentPane().add(btnProceed);
        btnProceed.setBounds(268, 622, 90, 23);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEMESTER :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 390, 84, 17);

        cmbSemester.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st SEMESTER", "2nd SEMESTER", " " }));
        cmbSemester.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbSemester);
        cmbSemester.setBounds(60, 413, 292, 24);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSOA/images/08493a54-2351-449f-b885-16faf39d49e4 (1) (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSOA/images/8b7cc5db-0cc4-4be5-8727-92724c565529 (1).jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 90, 400, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
                                                 
    
    String id = txtID.getText();
    String name = txtName.getText();
    String course = txtCourse.getText();
    String year = cmbYear.getSelectedItem().toString();
    String semester = cmbSemester.getSelectedItem().toString();

    // Tuition Fee Calculation
    int units = Integer.parseInt(txtUnits.getText());
    double tuitionFee = units * 987.5;

    // Scholarship discount
    String scholarship = cmbScholarship.getSelectedItem().toString().toLowerCase();
    
    double discountRate = switch (scholarship) {
        case "presidential", "working" -> 0.90;
        case "academic" -> 0.80;
        case "atheletic" -> 0.70;
        case "sugbo" -> 0.20;
        default -> 0;
    };

    double discountedTuition = tuitionFee - (tuitionFee * discountRate);

   
    double miscFee = 0;
    if (chkLibrary.isSelected()) miscFee += 1500;
    if (chkLaboratory.isSelected()) miscFee += 2000;
    if (chkClinic.isSelected()) miscFee += 1000;
    if (chkLms.isSelected()) miscFee += 500;

    double outstandingBalance = discountedTuition + miscFee;

    JavaSOAslip slip = new JavaSOAslip(
            id, name, course, year, semester,
            tuitionFee, scholarship, miscFee, outstandingBalance
    );

    slip.setVisible(true);
    this.dispose(); 


    }//GEN-LAST:event_btnProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JavaSOA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProceed;
    private javax.swing.JCheckBox chkClinic;
    private javax.swing.JCheckBox chkLaboratory;
    private javax.swing.JCheckBox chkLibrary;
    private javax.swing.JCheckBox chkLms;
    private javax.swing.JComboBox<String> cmbScholarship;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUnits;
    // End of variables declaration//GEN-END:variables
}
