/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jSOA;

/**
 *
 * @author jabi
 */
public class JavaSOAslip extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JavaSOAslip.class.getName());
            public JavaSOAslip(String id, String name, String course,String year, String semester,
                         double tuitionFee, String scholarship,
                         double misc, double balance) {
    /**
     * Creates new form JavaSOAslip
     */
    
        initComponents();
        lblID.setText(id);
        lblName.setText(name);
        lblCourse.setText(course);
        lblYear.setText(year);
        lblSemester.setText(semester);
        lblTuition.setText(String.format("₱ %.2f", tuitionFee));
        lblScholarship.setText(scholarship);
        lblMisc.setText(String.format("₱ %.2f", misc));
        lblBalance.setText(String.format("₱ %.2f", balance));
    }

    private JavaSOAslip() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblScholarship = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMisc = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTuition = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECIEPT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 90, 78, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 49, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID NUMBER :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 110, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COURSE : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 230, 71, 17);

        lblID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblID);
        lblID.setBounds(60, 200, 265, 19);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblName);
        lblName.setBounds(60, 150, 265, 19);

        lblCourse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblCourse);
        lblCourse.setBounds(60, 260, 265, 19);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("YEAR LEVEL :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 290, 93, 17);

        lblSemester.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(255, 255, 255));
        lblSemester.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblSemester);
        lblSemester.setBounds(60, 360, 265, 19);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SEMESTER :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 340, 84, 17);

        lblYear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblYear.setForeground(new java.awt.Color(255, 255, 255));
        lblYear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblYear);
        lblYear.setBounds(60, 310, 265, 19);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SCHOLARSHIP :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 440, 107, 17);

        lblScholarship.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblScholarship.setForeground(new java.awt.Color(255, 255, 255));
        lblScholarship.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblScholarship);
        lblScholarship.setBounds(60, 460, 265, 19);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MISCELLANEOUS :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 490, 127, 17);

        lblMisc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMisc.setForeground(new java.awt.Color(255, 255, 255));
        lblMisc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblMisc);
        lblMisc.setBounds(60, 510, 265, 19);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("OUTSTANDING BALANCE :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 540, 177, 17);

        lblBalance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblBalance);
        lblBalance.setBounds(60, 560, 265, 19);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TUITION FEE :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 390, 94, 17);

        lblTuition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTuition.setForeground(new java.awt.Color(255, 255, 255));
        lblTuition.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lblTuition);
        lblTuition.setBounds(60, 410, 259, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSOA/images/08493a54-2351-449f-b885-16faf39d49e4 (1) (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSOA/images/dark-blue-background-in-polygonal-style-vector (1).jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 70, 400, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JavaSOAslip().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMisc;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblScholarship;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTuition;
    private javax.swing.JLabel lblYear;
    // End of variables declaration//GEN-END:variables
}
